[build]
nixpacks = true
builder = "nixpacks"

[build.args]
PYTHON_VERSION = "3.11"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:${PORT}"

[apt]
packages = [
  "libgl1",
  "libglib2.0-0",
  "libglvnd0",
  "libglx0",
  "libxext6",
  "libxrender1"
]
